/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./**/*.html", "./*.html"],
  theme: {
    extend: {
      colors: {
        chamois: {
          50: "#fbf8ef",
          100: "#f3ead2",
          200: "#ebdbb2",
          300: "#dab86f",
          400: "#d1a14e",
          500: "#c78739",
          600: "#b06a2f",
          700: "#92502b",
          800: "#784028",
          900: "#633624",
          950: "#381b10",
        },
        "mine-shaft": {
          50: "#f6f6f6",
          100: "#e7e7e7",
          200: "#d1d1d1",
          300: "#b0b0b0",
          400: "#888888",
          500: "#6d6d6d",
          600: "#5d5d5d",
          700: "#4f4f4f",
          800: "#454545",
          900: "#3d3d3d",
          950: "#282828",
        },
        accent: "#98971a",
      },
      typography: ({ theme }) => ({
        archive: {
          css: {
            "--tw-prose-body": theme("colors.mine-shaft[950]"),
            "--tw-prose-headings": theme("colors.mine-shaft[950]"),
            "--tw-prose-lead": theme("colors.mine-shaft[700]"),
            "--tw-prose-links": theme("colors.mine-shaft[950]"),
            "--tw-prose-bold": theme("colors.mine-shaft[950]"),
            "--tw-prose-counters": theme("colors.mine-shaft[600]"),
            "--tw-prose-bullets": theme("colors.mine-shaft[400]"),
            "--tw-prose-hr": theme("colors.mine-shaft[300]"),
            "--tw-prose-quotes": theme("colors.mine-shaft[950]"),
            "--tw-prose-quote-borders": theme("colors.mine-shaft[300]"),
            "--tw-prose-captions": theme("colors.mine-shaft[700]"),
            "--tw-prose-code": theme("colors.mine-shaft[950]"),
            "--tw-prose-pre-code": theme("colors.mine-shaft[100]"),
            "--tw-prose-pre-bg": theme("colors.mine-shaft[950]"),
            "--tw-prose-th-borders": theme("colors.mine-shaft[300]"),
            "--tw-prose-td-borders": theme("colors.mine-shaft[200]"),
            "--tw-prose-invert-body": theme("colors.chamois[200]"),
            "--tw-prose-invert-headings": theme("colors.chamois[200]"),
            "--tw-prose-invert-lead": theme("colors.chamois[300]"),
            "--tw-prose-invert-links": theme("colors.chamois[200]"),
            "--tw-prose-invert-bold": theme("colors.chamois[200]"),
            "--tw-prose-invert-counters": theme("colors.chamois[400]"),
            "--tw-prose-invert-bullets": theme("colors.chamois[600]"),
            "--tw-prose-invert-hr": theme("colors.mine-shaft[700]"),
            "--tw-prose-invert-quotes": theme("colors.chamois[100]"),
            "--tw-prose-invert-quote-borders": theme("colors.mine-shaft[700]"),
            "--tw-prose-invert-captions": theme("colors.chamois[400]"),
            "--tw-prose-invert-code": theme("colors.chamois[200]"),
            "--tw-prose-invert-pre-code": theme("colors.chamois[300]"),
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": theme("colors.chamois[600]"),
            "--tw-prose-invert-td-borders": theme("colors.mine-shaft[700]"),
          },
        },
      }),
    },
    fontFamily: {
      math: ["Computer Modern", "ui-serif", "serif"],
      serif: ["IBM Plex Serif", "ui-serif", "Georgia", "serif"],
      sans: ["Fira Sans", "sans"],
      mono: ["Fira Mono", "ui-monospace", "SFMono-Regular"],
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
